appDev/urls.py
from django.conf import settings
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path



from feed import urls as feeds_urls

from testimonial import urls as testimonials_urls

urlpatterns = [
    path('', include(feeds_urls, namespace='feed')),
    path('', include(testimonials_urls, namespace='testimonials')),
    url('', include('allauth.urls')),
    
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/urls.py
from django.urls import path
from . import views
from .views import feedPageView, feedDetailView


app_name = 'feed'

urlpatterns = [
    path('', views.feedPageView.as_view(), name='index'),
    path('detail/<int:pk>/', views.feedDetailView.as_view(), name='detail')
    
]

testimonial/urls.py
from django.urls import path
from . import views
from testimonial.views import TestimonialPageView


app_name = 'testimonial'

urlpatterns = [
    path('', views.TestimonialPageView.as_view(), name='testimonial'),
    
]

about/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post (models.Model):
    location_choices = [
        ('Auckland, New Zealand','AKL'),
        ( 'Wellington, New Zealand', 'WLG'),
        ('Christchurch, New Zealand', 'CHC'),
        ('Queenstown, New Zealand', 'QT'),
        ]
    
    location = models.CharField(max_length=50, choices=location_choices) 
    quote = models.CharField(max_length=240, blank=False, null=False)
    description = models.TextField() 
    image = ImageField() 
    
    def  __str__(self) -> str: # this command ensure that the title is displayed correctly in the backend
        return self.quote[0:100]

portfolio/models.py
from django.db import models

# Create your models here.

pricing/models.py
from django.db import models

class Post (models.Model):
    service_choices = [
        ('Web Design'),
        ('Video Production'),
        ('Graphics Design'),
        ('Animation'),
    ]
    
    service = models.CharField(max_length=50, choices=service_choices)
    price = models.IntegerField()
    contents = models.BooleanField()
    
    
    pass

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    """ From django user profile we are creating a OnetoOneField which in turn
    merges our user profile with the django one."""
    
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    def  __str__(self): # this command ensure that the title is displayed correctly in the backend
        return self.user.username
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
        
    """ Create a new Profile() object when Django User is created """
    
    if created:
        Profile.objects.create(user=instance)

services/models.py
from django.db import models

# Create your models here.

testimonial/models.py
from django.db import models
from sorl.thumbnail import ImageField

# Create your models here.
class Testimonial (models.Model):
    date = models.DateField(auto_now='auto')
    name = models.CharField(max_length=50, blank=False, null=False)
    quote = models.TextField(max_length=550, blank=False, null=False)
    image = models.ImageField( )
    
    def  __str__(self) -> str: # this command ensure that the title is displayed correctly in the backend
        return self.name[0:50]

feed/views.py
from typing import Text
from django.db import models
from django.views.generic import ListView,DetailView,TemplateView

from .models import Post

from django.contrib import messages # import messages from django.contrib


class feedPageView(TemplateView):
    http_method_names = ['get']
    template_name = 'home.html'
    model = Post
    context_object_name = 'posts'  
    queryset = Post.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')[0:1] # Django get all of the posts and order them by their id descending
        return context

class feedDetailView(DetailView):
    template_name='detail.html'
    model=Post

pricing/views.py
from typing import Text
from django.db import models
from django.views.generic import ListView,DetailView,TemplateView

profiles/views.py
from django.shortcuts import render

# Create your views here.

testimonial/views.py
from typing import Text
from django.db import models
from django.views.generic import TemplateView

from .models import Testimonial

from django.contrib import messages # import messages from django.contrib


class TestimonialPageView(TemplateView):
    http_method_names = ['get']
    template_name = 'home.html'
    model = Testimonial
    context_object_name = 'testimonials'  
    queryset = Testimonial.objects.all().order_by('-id')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['testimonials'] = Testimonial.objects.all().order_by('-id')[0:3] # Django get all of the posts and order them by their id descending
        return context

templates/about.html
{% extends 'base.html' %}
{% block title %}About Us{% endblock %}

{% block body %}
    
{% endblock %} 

templates/base.html
{% load static %}
 
<!DOCTYPE html>
<html lang="en-nz">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href=" {% static '/css/style.css' %}">

    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.4/dist/tailwind.min.css">
 
    <link rel="stylesheet" href=" {% static '/css/bootstrap.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.min.css">
   
    <title>{% block title %}Motion Magic Pictures{% endblock %}</title>
</head>
<body>

    {% include 'includes/navbar.html' %}
    
    {% block body %}

        <div class="container-md mx-auto">
            {% block content %}{% endblock%}
        </div>

    {% endblock %}  

    {% include 'includes/pricing.html' %}

    {% include 'includes/footer.html' %}
     
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %}Get In Touch{% endblock %}
{% block body %}
    
{% endblock %} 

templates/detail.html
{% extends 'base.html' %}


{% block title %}{{post.quote}}{% endblock %}

{%block body %}
{% include 'includes/post.html' with post=post %}
{% endblock %} 

templates/home.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Creativity Made Simple{% endblock %}

{% block body %}

{% include 'includes/header.html' %}

<div class="container-fluid">

{# TODO: I need to create the layout for the full home page as from XD file#}

    <div class="row py-3 bg-gray-100">
    
        {% for post in posts %}
    
        <div class=" lg:py-12 lg:flex lg:justify-center">
            <div class="bg-white lg:mx-8 lg:flex lg:max-w-5xl lg:shadow-lg lg:rounded-lg">
                <div class="lg:w-1/2">
                    <div class="h-64 bg-cover lg:rounded-lg lg:h-full" style="background-image:url('{{post.image.url}}')"></div>
                </div>
                <div class="py-12 px-6 max-w-xl lg:max-w-5xl lg:w-1/2">
                    <h6 class="text-gray-600">{{post.location}}</h6>
                    <h2 class="text-3xl text-gray-800 font-bold text-uppercase">{{post.quote}}</h2>
                    <p class="mt-4 text-gray-600">{{post.description|truncatewords:100}}</p>
                    <div class="mt-8">
                        <a href="{% url 'feed:detail' post.id %}" class="bg-gray-900 text-gray-100 px-5 py-3 font-semibold rounded"> Read More</a>
                    </div>
                </div>
            </div>
        </div>
    
        {% endfor %} 
    
    </div>

    <div class="row py-3 bg-gray-100">
        <div class="container-md" style="min-height: 450pt;">

            {% for testimonial in testimonials %}
        
            {{testimonial.date}}
            <h1>{{testimonial.name}}</h1>
            <h1>{{testimonial.quote}}</h1> 
            <img src="{{testimonial.image.url}}" alt="">
        
            {% endfor %}
        </div>
    </div>
    

</div>





{% endblock %} 

templates/includes/footer.html
{% load static %}

<!-- JavaScript Bundle with Popper -->
<script src="{% static '/js/bootstrap.js' %}" crossorigin="anonymous"></script>

<footer >
    <div class="footer fixed" style="min-height: 450pt; background-color: black"> </div>

</footer>

templates/includes/header.html
 {# TODO: I need to find a slider from https://tailwindcomponents.com/ #}
 {%load static%}

<div class="container-fluid" style="margin: 0; padding: 0" > 
        <!-- HERO SECTION -->
        
            <div class="z-30 relative items-center justify-center w-full w-screen h-screen">
                <div>
                    <div class="inset-0  w-full h-screen">
                        <!-- <video 
                            src="https://youtu.be/OhyQRljsp2w" 
                            autoplay 
                            muted 
                            loop 
                            class="object-cover w-full h-full"
                        >
                        </video>      -->
                         <iframe class="object-cover w-full h-full" src="https://www.youtube-nocookie.com/embed/lwtFl0WrzAY?controls=0"  title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    
                    </div>    
                </div>
            </div>
        <!-- HERO SECTION END -->
</div>

templates/includes/navbar.html
  {% load static %}
  {% load thumbnail %}

  {# TODO: Conclude if this is the best navbar for the job or if it needs changing using https://tailwindcomponents.com/ #}
  <nav class="navbar sticky-top navbar-light bg-dark-5 "  style="min-height: 90px;">
    <div class="container-sm">

      <img src="{% static 'media/colorLogo.png'%}" alt="Colour Logo" width="70" height="70">
      
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel"><img class="text-center" src="{% static 'media/colorLogo.png'%}" alt="Colour Logo" width="100" height="100"> </h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body  ">
        <ul class="navbar-nav justify-content-end flex-grow-1 py-3 " style="color: black;">
          
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
           
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Portfolio
            </a>
              
            <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                <li><a class="dropdown-item" href="#">Full Portfolio</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Visual FX</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Graphics Design</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Motion Graphics</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Corporate Branding</a></li>
                <hr class="dropdown-divider">
                
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link" href="#">Get In touch</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Enquiries: info@motionmagicpictures.co.nz</a>
        </li>

        {% if request.user.is_authenticated  %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account_logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account_login' %}">Login</a>
        </li>
        {% endif %}
        

        
        </ul>


          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
  </nav>

templates/includes/post.html
    {% load thumbnail %}
    
    <div class="container-fluid absolute inset-0 object-cover h-48 w-96 " style="background-image:url('{{object.image.url}}'); background-repeat: no-repeat;background-size: 100% ;min-height:450pt"> 
     
    </div>
      
    <div class="container-md justify-content-center rounded my-5">
            <main class="relative container mx-auto bg-white px-4 ">
            <div class="relative -mx-4 top-0 pt-[17%] overflow-hidden">
              <img class="absolute inset-0 object-cover object-top w-full h-full filter blur" src="{{object.image.url}}" alt="" />
            </div>
          
            <div class="mt-[-10%] w-1/2 mx-5">
              <div class="relative pt-[56.25%] overflow-hidden rounded-2xl">
                <img class="w-full h-full absolute inset-0 object-cover" src="{{object.image.url}}" alt="" />
              </div>
            </div>
          
            <article class="max-w-prose mx-auto py-8">
              <h1 class="text-2xl font-bold">{{object.quote}}</h1>
              <h2 class="mt-2 text-sm text-gray-500">{{object.location}}</h2>
          
              <p class="mt-6">{{object.description}}</p>
              <a href="{%url 'feed:index' %}">&lAarr; Return to Home</a>
              </article>

             
          </main>
    
    
        </div>

templates/includes/pricing.html
<div class="min-w-screen min-h-screen bg-gray-100 py-5">
    
    <div class="w-full mx-auto bg-white px-5 py-10 text-gray-600  mb-10">
        <div class="text-center max-w-xl mx-auto">
            <h1 class="text-5xl md:text-6xl font-bold mb-5">Pricing</h1>
            <h3 class="text-xl font-medium mb-10">Lorem ipsum dolor sit amet consectetur adipisicing elit repellat dignissimos laboriosam odit accusamus porro</h3>
        </div>
        <div class="max-w-4xl mx-auto md:flex">
            <div class="w-full md:w-1/3 md:max-w-none bg-white px-8 md:px-10 py-8 md:py-10 mb-3 mx-auto md:my-6 rounded-md shadow-lg shadow-gray-600 md:flex md:flex-col">
                <div class="w-full flex-grow">
                    <h2 class="text-center font-bold uppercase mb-4">PERSONAL</h2>
                    <h3 class="text-center font-bold text-4xl mb-5">$5/mo</h3>
                    <ul class="text-sm px-5 mb-8">
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Lorem ipsum</li>
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Dolor sit amet</li>
                    </ul>
                </div>
                <div class="w-full">
                    <button class="font-bold bg-gray-600 hover:bg-gray-700 text-white rounded-md px-10 py-2 transition-colors w-full">Buy Now</button>
                </div>
            </div>
            <div class="w-full md:w-1/3 md:max-w-none bg-white px-8 md:px-10 py-8 md:py-10 mb-3 mx-auto md:-mx-3 md:mb-0 rounded-md shadow-lg shadow-gray-600 md:relative md:z-50 md:flex md:flex-col">
                <div class="w-full flex-grow">
                    <h2 class="text-center font-bold uppercase mb-4">TEAM</h2>
                    <h3 class="text-center font-bold text-4xl md:text-5xl mb-5">$15/mo</h3>
                    <ul class="text-sm px-5 mb-8">
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Lorem ipsum</li>
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Dolor sit amet</li>
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Consectetur</li>
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Adipisicing</li>
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Elit repellat</li>
                    </ul>
                </div>
                <div class="w-full">
                    <button class="font-bold bg-gray-600 hover:bg-gray-700 text-white rounded-md px-10 py-2 transition-colors w-full">Buy Now</button>
                </div>
            </div>
            <div class="w-full md:w-1/3 md:max-w-none bg-white px-8 md:px-10 py-8 md:py-10 mb-3 mx-auto md:my-6 rounded-md shadow-lg shadow-gray-600 md:flex md:flex-col">
                <div class="w-full flex-grow">
                    <h2 class="text-center font-bold uppercase mb-4">PRO</h2>
                    <h3 class="text-center font-bold text-4xl mb-5">$35/mo</h3>
                    <ul class="text-sm px-5 mb-8">
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Lorem ipsum</li>
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Dolor sit amet</li>
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Consectetur</li>
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Adipisicing</li>
                        <li class="leading-tight"><i class="mdi mdi-check-bold text-lg"></i> Much more...</li>
                    </ul>
                </div>
                <div class="w-full">
                    <button class="font-bold bg-gray-600 hover:bg-gray-700 text-white rounded-md px-10 py-2 transition-colors w-full">Buy Now</button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/portfolio.html
{% extends 'base.html' %}

{% block title %}Portfolio{% endblock %}

{% block body %}
    
{% endblock %} 

templates/services.html
{% extends 'base.html' %}

{% block title %}Services{% endblock %}

{% block body %}
    
{% endblock %} 